import {
  Achievement,
  AchievementType,
  RoomType,
  Task,
  TaskType,
} from '@prisma/client';

export const achievements: Achievement[] = [
  {
    id: 1,
    name: 'Упорный',
    levels: [1, 2, 3],
    type: AchievementType.STREAK,
    values: [7, 28, 90],
  },
  {
    id: 2,
    name: 'Чистюля',
    levels: [1, 2, 3],
    type: AchievementType.POINTS,
    values: [100, 1000, 5000],
  },
  {
    id: 3,
    name: 'Главный по чек-листам',
    levels: [1, 2, 3],
    type: AchievementType.CHECKLISTS_COMPLETED,
    values: [7, 90, 180],
  },
  {
    id: 4,
    name: 'Бронзовая лига',
    levels: [1],
    type: AchievementType.BRONZE_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 5,
    name: 'Серебрянная лига',
    levels: [1],
    type: AchievementType.SILVER_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 6,
    name: 'Золотая лига',
    levels: [1],
    type: AchievementType.GOLD_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 7,
    name: 'Платиновая лига',
    levels: [1],
    type: AchievementType.PLATINUM_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 8,
    name: 'Алмазная лига',
    levels: [1],
    type: AchievementType.DIAMOND_LEAGUE_REACHED,
    values: [1],
  },
];

export const tasks: Task[] = [
  {
    id: 1,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.KITCHEN,
    description: 'Протереть столы на кухне влажной тряпкой',
    reward: 10,
  },
  {
    id: 2,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.KITCHEN,
    description:
      'Протереть стены и вертикальные поверхности на кухне влажной тряпкой',
    reward: 12,
  },
  {
    id: 3,
    type: TaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: RoomType.EVERYWHERE,
    description: 'Пропылесосить полы',
    reward: 20,
  },
  {
    id: 4,
    type: TaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: RoomType.EVERYWHERE,
    description: 'Пропылесосить ковры',
    reward: 10,
  },
  {
    id: 5,
    type: TaskType.DISHWASHING,
    room: RoomType.KITCHEN,
    description: 'Помыть грязную посуду',
    reward: 10,
  },
  {
    id: 6,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.LIVING_ROOM,
    description: 'Протереть столы в зале влажной тряпкой',
    reward: 10,
  },
  {
    id: 7,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Протереть дверные ручки и выключатели',
    reward: 5,
  },
  {
    id: 8,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Помыть полы',
    reward: 30,
  },
  {
    id: 9,
    type: TaskType.LAUNDRY,
    room: RoomType.GENERAL,
    description: 'Постирать и развесить одежду',
    reward: 10,
  },
  {
    id: 10,
    type: TaskType.DISHWASHING,
    room: RoomType.KITCHEN,
    description: 'Почистить раковину',
    reward: 12,
  },
  {
    id: 11,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Вымыть подоконники влажной тряпкой',
    reward: 8,
  },
  {
    id: 12,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Протереть зеркала и стеклянные поверхности',
    reward: 11,
  },
  {
    id: 13,
    type: TaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: RoomType.LIVING_ROOM,
    description: 'Пропылесосить мебель и кресла',
    reward: 13,
  },
  {
    id: 14,
    type: TaskType.FURNITURE,
    room: RoomType.KITCHEN,
    description: 'Почистить микроволновку и плиту',
    reward: 15,
  },
  {
    id: 15,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Протереть полки и шкафы',
    reward: 12,
  },
  {
    id: 16,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Помыть окна и рамы',
    reward: 18,
  },
  {
    id: 17,
    type: TaskType.FURNITURE,
    room: RoomType.BEDROOM,
    description: 'Поменять постельное белье',
    reward: 14,
  },
  {
    id: 18,
    type: TaskType.FURNITURE,
    room: RoomType.BATHROOM,
    description: 'Вымыть ванну/душевую кабинку',
    reward: 14,
  },
  {
    id: 19,
    type: TaskType.FURNITURE,
    room: RoomType.BATHROOM,
    description: 'Вымыть раковину в ванной',
    reward: 14,
  },
  {
    id: 20,
    type: TaskType.FURNITURE,
    room: RoomType.BATHROOM,
    description: 'Вымыть унитаз',
    reward: 14,
  },
  {
    id: 21,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.OFFICE,
    description: 'Протереть рабочее место влажной тряпкой',
    reward: 14,
  },
  {
    id: 22,
    type: TaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: RoomType.OFFICE,
    description: 'Пропылесосить рабочее место',
    reward: 14,
  },
  {
    id: 23,
    type: TaskType.FURNITURE,
    room: RoomType.GARAGE,
    description: 'Помыть машину',
    reward: 14,
  },
  {
    id: 24,
    type: TaskType.WASTE_DISPOSING,
    room: RoomType.GENERAL,
    description: 'Выбросить мусор',
    reward: 10,
  },
  {
    id: 25,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Протереть электронику',
    reward: 8,
  },
];
