import {
  Achievement,
  AchievementType,
  RoomType,
  Task,
  TaskType,
} from '@prisma/client';

export const achievements: Achievement[] = [
  {
    id: 1,
    name: 'Упорный',
    levels: [1, 2, 3],
    type: AchievementType.STREAK,
    values: [7, 28, 90],
  },
  {
    id: 2,
    name: 'Фермер чубриков',
    levels: [1, 2, 3],
    type: AchievementType.CHUBRIKS_GROWN,
    values: [1, 3, 5],
  },
  {
    id: 3,
    name: 'Ухажер за чубриком',
    levels: [1, 2, 3],
    type: AchievementType.CHUBRIK_PHASE_REACHED,
    values: [2, 3, 4],
  },
  {
    id: 4,
    name: 'Обидчик чубриков',
    levels: [1, 2, 3],
    type: AchievementType.CHUBRIKS_GONE,
    values: [10, 20, 30],
  },
];

export const tasks: Task[] = [
  {
    id: 1,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.KITCHEN,
    description: 'Протереть столы влажной тряпкой',
  },
  {
    id: 2,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.KITCHEN,
    description: 'Протереть вертикальные поверхности влажной тряпкой',
  },
  {
    id: 3,
    type: TaskType.DISHWASHING,
    room: RoomType.KITCHEN,
    description: 'Помыть грязную посуду',
  },
  {
    id: 4,
    type: TaskType.FURNITURE,
    room: RoomType.KITCHEN,
    description: 'Почистить раковину',
  },
  {
    id: 5,
    type: TaskType.FURNITURE,
    room: RoomType.KITCHEN,
    description: 'Почистить микроволновку и плиту',
  },
  {
    id: 6,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.KITCHEN,
    description: 'Помыть пол',
  },
  {
    id: 7,
    type: TaskType.FURNITURE,
    room: RoomType.BATHROOM,
    description: 'Вымыть ванну/душевую кабинку',
  },
  {
    id: 8,
    type: TaskType.FURNITURE,
    room: RoomType.BATHROOM,
    description: 'Почистить раковину',
  },
  {
    id: 9,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.BATHROOM,
    description: 'Протереть зеркало',
  },
  {
    id: 10,
    type: TaskType.FURNITURE,
    room: RoomType.BATHROOM,
    description: 'Почистить унитаз',
  },
  {
    id: 11,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.BATHROOM,
    description: 'Помыть пол',
  },
  {
    id: 12,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.LIVING_ROOM,
    description: 'Протереть столы влажной тряпкой',
  },
  {
    id: 13,
    type: TaskType.VACUUMING,
    room: RoomType.LIVING_ROOM,
    description: 'Пропылесосить диваны и кресла',
  },
  {
    id: 14,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.LIVING_ROOM,
    description: 'Помыть пол',
  },
  {
    id: 15,
    type: TaskType.FURNITURE,
    room: RoomType.BEDROOM,
    description: 'Поменять постельное белье',
  },
  {
    id: 16,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.BEDROOM,
    description: 'Протереть столы влажной тряпкой',
  },
  {
    id: 17,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.BEDROOM,
    description: 'Помыть пол',
  },
  {
    id: 18,
    type: TaskType.FURNITURE,
    room: RoomType.OFFICE,
    description: 'Протереть рабочее место влажной тряпкой',
  },
  {
    id: 19,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.OFFICE,
    description: 'Помыть пол',
  },
  {
    id: 20,
    type: TaskType.VACUUMING,
    room: RoomType.EVERYWHERE,
    description: 'Пропылесосить полы',
  },
  {
    id: 21,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Протереть дверные ручки и выключатели',
  },
  {
    id: 22,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Вымыть подоконники влажной тряпкой',
  },
  {
    id: 23,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Протереть зеркала и стеклянные поверхности',
  },
  {
    id: 24,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Протереть полки и шкафы',
  },
  {
    id: 25,
    type: TaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: RoomType.EVERYWHERE,
    description: 'Помыть окна и рамы',
  },
  {
    id: 26,
    type: TaskType.FURNITURE,
    room: RoomType.EVERYWHERE,
    description: 'Протереть электронику',
  },
  {
    id: 27,
    type: TaskType.DAILY,
    room: RoomType.EVERYWHERE,
    description: 'Выбросить мусор',
  },
  {
    id: 28,
    type: TaskType.DAILY,
    room: RoomType.EVERYWHERE,
    description: 'Проветрить помещения',
  },
  {
    id: 29,
    type: TaskType.DAILY,
    room: RoomType.DINING_ROOM,
    description: 'Протереть стол',
  },
  {
    id: 30,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.DINING_ROOM,
    description: 'Помыть пол',
  },
  {
    id: 31,
    type: TaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: RoomType.BASEMENT,
    description: 'Помыть пол',
  },
  {
    id: 32,
    type: TaskType.LAUNDRY,
    room: RoomType.GENERAL,
    description: 'Постирать и развесить одежду',
  },
  {
    id: 33,
    type: TaskType.LAUNDRY,
    room: RoomType.GENERAL,
    description: 'Снять одежду с сушки',
  },
  {
    id: 34,
    type: TaskType.LAUNDRY,
    room: RoomType.GENERAL,
    description: 'Погладить одежду',
  },
  {
    id: 35,
    type: TaskType.DAILY,
    room: RoomType.GENERAL,
    description: 'Убрать детские игрушки',
  },
];
