import { IAchievement, ITask } from 'src/common/interfaces';
import { EAchievementType, ETaskType, ERoom } from 'src/common/enums';

export const achievements: IAchievement[] = [
  {
    id: 1,
    name: 'Упорный',
    levels: [1, 2, 3],
    type: EAchievementType.STREAK,
    values: [7, 28, 90],
  },
  {
    id: 2,
    name: 'Чистюля',
    levels: [1, 2, 3],
    type: EAchievementType.POINTS,
    values: [100, 1000, 5000],
  },
  {
    id: 3,
    name: 'Главный по чек-листам',
    levels: [1, 2, 3],
    type: EAchievementType.CHECKLISTS_COMPLETED,
    values: [7, 90, 180],
  },
  {
    id: 4,
    name: 'Бронзовая лига',
    levels: [1],
    type: EAchievementType.BRONZE_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 5,
    name: 'Серебрянная лига',
    levels: [1],
    type: EAchievementType.SILVER_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 6,
    name: 'Золотая лига',
    levels: [1],
    type: EAchievementType.GOLD_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 7,
    name: 'Платиновая лига',
    levels: [1],
    type: EAchievementType.PLATINUM_LEAGUE_REACHED,
    values: [1],
  },
  {
    id: 8,
    name: 'Алмазная лига',
    levels: [1],
    type: EAchievementType.DIAMOND_LEAGUE_REACHED,
    values: [1],
  },
];

export const tasks: ITask[] = [
  {
    id: 1,
    type: ETaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: ERoom.KITCHEN,
    description: 'Протереть столы на кухне влажной тряпкой',
    reward: 10,
  },
  {
    id: 2,
    type: ETaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: ERoom.KITCHEN,
    description:
      'Протереть стены и вертикальные поверхности на кухне влажной тряпкой',
    reward: 12,
  },
  {
    id: 3,
    type: ETaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: ERoom.EVERYWHERE,
    description: 'Пропылесосить полы',
    reward: 20,
  },
  {
    id: 4,
    type: ETaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: ERoom.EVERYWHERE,
    description: 'Пропылесосить ковры',
    reward: 10,
  },
  {
    id: 5,
    type: ETaskType.DISHWASHING,
    room: ERoom.KITCHEN,
    description: 'Помыть грязную посуду',
    reward: 10,
  },
  {
    id: 6,
    type: ETaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: ERoom.LIVING_ROOM,
    description: 'Протереть столы в зале влажной тряпкой',
    reward: 10,
  },
  {
    id: 7,
    type: ETaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: ERoom.EVERYWHERE,
    description: 'Протереть дверные ручки и выключатели',
    reward: 5,
  },
  {
    id: 8,
    type: ETaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: ERoom.EVERYWHERE,
    description: 'Помыть полы',
    reward: 30,
  },
  {
    id: 9,
    type: ETaskType.LAUNDRY,
    room: ERoom.BATHROOM,
    description: 'Постирать и развесить одежду',
    reward: 10,
  },
  {
    id: 10,
    type: ETaskType.DISHWASHING,
    room: ERoom.KITCHEN,
    description: 'Почистить раковину',
    reward: 12,
  },
  {
    id: 11,
    type: ETaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: ERoom.EVERYWHERE,
    description: 'Вымыть подоконники влажной тряпкой',
    reward: 8,
  },
  {
    id: 12,
    type: ETaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: ERoom.EVERYWHERE,
    description: 'Протереть зеркала и стеклянные поверхности',
    reward: 11,
  },
  {
    id: 13,
    type: ETaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: ERoom.LIVING_ROOM,
    description: 'Пропылесосить мебель и кресла',
    reward: 13,
  },
  {
    id: 14,
    type: ETaskType.FURNITURE,
    room: ERoom.KITCHEN,
    description: 'Почистить микроволновку и плиту',
    reward: 15,
  },
  {
    id: 15,
    type: ETaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: ERoom.EVERYWHERE,
    description: 'Протереть полки и шкафы',
    reward: 12,
  },
  {
    id: 16,
    type: ETaskType.VERTICAL_SURFACES_WET_CLEANING,
    room: ERoom.EVERYWHERE,
    description: 'Помыть окна и рамы',
    reward: 18,
  },
  {
    id: 17,
    type: ETaskType.FURNITURE,
    room: ERoom.BEDROOM,
    description: 'Поменять постельное белье',
    reward: 14,
  },
  {
    id: 18,
    type: ETaskType.FURNITURE,
    room: ERoom.BATHROOM,
    description: 'Вымыть ванну/душевую кабинку',
    reward: 14,
  },
  {
    id: 19,
    type: ETaskType.FURNITURE,
    room: ERoom.BATHROOM,
    description: 'Вымыть раковину в ванной',
    reward: 14,
  },
  {
    id: 20,
    type: ETaskType.FURNITURE,
    room: ERoom.BATHROOM,
    description: 'Вымыть унитаз',
    reward: 14,
  },
  {
    id: 22,
    type: ETaskType.HORIZONTAL_SURFACES_WET_CLEANING,
    room: ERoom.OFFICE,
    description: 'Протереть рабочее место влажной тряпкой',
    reward: 14,
  },
  {
    id: 23,
    type: ETaskType.HORIZONTAL_SURFACES_VACUUMING,
    room: ERoom.OFFICE,
    description: 'Пропылесосить рабочее место',
    reward: 14,
  },
];
