export enum EAchievementType {
  STREAK,
  POINTS,
  CHECKLISTS_COMPLETED,
  BRONZE_LEAGUE_REACHED,
  SILVER_LEAGUE_REACHED,
  GOLD_LEAGUE_REACHED,
  PLATINUM_LEAGUE_REACHED,
  DIAMOND_LEAGUE_REACHED,
}

export enum ETaskType {
  HORIZONTAL_SURFACES_WET_CLEANING,
  VERTICAL_SURFACES_WET_CLEANING,
  HORIZONTAL_SURFACES_VACUUMING,
  LAUNDRY,
  DISHWASHING,
  FURNITURE,
}

export enum ERoom {
  KITCHEN,
  BATHROOM,
  LIVING_ROOM,
  BEDROOM,
  OFFICE,
  EVERYWHERE,
}
